blank_issues_enabled: false
contact_links:
  - name: Questions & Discussion
    url: https://github.com/Agile-Media-Agency/the-fluid-theme/discussions
    about: Ask questions, share ideas, or show what you've built
